### ISSUE TITLE
Make sure this project follows Stencil best practices

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers-lite#3]

**Comment by Jefiozie** [comment]
Hi @romulocintra, could you provide me some guidance on what the best practices are?
I can find some time to get this repo up to standards somewhere upcoming days, if you don't mind that I'm picking up this issue?

**Comment by romulocintra** [comment]
Hi @Jefiozie  happy that you taking over in reality no time at all...  More than have best practices on composing the xlayers-lite we should have a look in the issues i opened few time ago... some of them were directly related with existing code back on August(lot of things changed since ) and the goal was to split implementation in blocks.

About best practices stencil is so so small that is difficult to have any huge anti-pattern but will be reviewing PR and you have ionic as a great reference.

**Comment by Jefiozie** [comment]
Thanks @romulocintra I will look at ionic for now and add some extra linting rules to the repo.
